In [115]:
import pandas as pd

# Load the datasets

f1_circuits_df = pd.read_csv('F1Data/F1-circuits.csv', encoding='utf-8', sep=';')
circuits_df = pd.read_csv('F1Data/circuits.csv')

In [116]:
# Display the first few rows of each dataset
f1_circuits_df

,Circuit,Type,Direction,Location,Current Length,Grands Prix,Season(s),Grands Prix held
0,Adelaide Street Circuit,Street,Clockwise,"Adelaide, Australia",3.780 km (2.349 mi),Australian Grand Prix,1985-1995,11
1,Ain Diab,Road,Clockwise,"Casablanca, Morocco",7.618 km (4.734 mi),Moroccan Grand Prix,1958,1
2,Aintree,Road,Clockwise,"Liverpool, United Kingdom",4.828 km (3.000 mi),British Grand Prix,"1955, 1957, 1959, 1961-1962",5
3,Albert Park Grand Prix Circuit,Street,Clockwise,"Melbourne, Australia",5.303 km (3.295 mi),Australian Grand Prix,1996-2014,19
4,AVUS,Street,Anti-clockwise,"Berlin, Germany",8.300 km (5.157 mi),German Grand Prix,1959,1
...,...,...,...,...,...,...,...,...
64,Watkins Glen,Race,Clockwise,"Watkins Glen, United States",5.430 km (3.374 mi),United States Grand Prix,1961-1980,20
65,Yas Marina Circuit,Race,Anti-clockwise,"Abu Dhabi, United Arab Emirates",5.554 km (3.451 mi),Abu Dhabi Grand Prix,2009-2013,5
66,Circuit Park Zandvoort,Race,Clockwise,"Zandvoort, Netherlands",4.252 km (2.642 mi),Dutch Grand Prix,"1952-1953, 1955, 1958-1971, 1973-1985",30
67,Zeltweg,Road,Clockwise,"Zeltweg, Austria",3.186 km (1.980 mi),Austrian Grand Prix,1964,1
68,Zolder,Race,Clockwise,"Heusden-Zolder, Belgium",4.011 km (2.492 mi),Belgian Grand Prix,"1973, 1975-1982, 1984",10

In [117]:
circuits_df

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,MontmelÃ³,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park
...,...,...,...,...,...,...,...,...,...
72,75,portimao,AutÃ³dromo Internacional do Algarve,PortimÃ£o,Portugal,37.22700,-8.62670,108,http://en.wikipedia.org/wiki/Algarve_Internati...
73,76,mugello,Autodromo Internazionale del Mugello,Mugello,Italy,43.99750,11.37190,255,http://en.wikipedia.org/wiki/Mugello_Circuit
74,77,jeddah,Jeddah Corniche Circuit,Jeddah,Saudi Arabia,21.63190,39.10440,15,http://en.wikipedia.org/wiki/Jeddah_Street_Cir...
75,78,losail,Losail International Circuit,Al Daayen,Qatar,25.49000,51.45420,12,http://en.wikipedia.org/wiki/Losail_Internatio...
76,79,miami,Miami International Autodrome,Miami,USA,25.95810,-80.23890,0,http://en.wikipedia.org/wiki/Miami_Internation...

In [118]:
f1_circuits_df = f1_circuits_df[['Circuit']]
f1_circuits_df

                           Circuit
0          Adelaide Street Circuit
1                         Ain Diab
2                          Aintree
3   Albert Park Grand Prix Circuit
4                             AVUS
..                             ...
64                    Watkins Glen
65              Yas Marina Circuit
66          Circuit Park Zandvoort
67                         Zeltweg
68                          Zolder

[69 rows x 1 columns]

In [119]:
circuits_df = circuits_df[['name']]
circuits_df

                                    name
0         Albert Park Grand Prix Circuit
1           Sepang International Circuit
2          Bahrain International Circuit
3         Circuit de Barcelona-Catalunya
4                          Istanbul Park
..                                   ...
72    AutÃ³dromo Internacional do Algarve
73  Autodromo Internazionale del Mugello
74               Jeddah Corniche Circuit
75          Losail International Circuit
76         Miami International Autodrome

[77 rows x 1 columns]

In [120]:
# Extract unique values from both DataFrames
f1_unique = f1_circuits_df['Circuit'].unique()
circuits_unique = circuits_df['name'].unique()

# Find matching values
matching = set(f1_unique) & set(circuits_unique)

# Find non-matching values in f1_circuits_df
non_matching_f1 = set(f1_unique) - set(circuits_unique)

# Find non-matching values in circuits_df
non_matching_circuits = set(circuits_unique) - set(f1_unique)

# Display the results
print(matching)
print(non_matching_f1)
print(non_matching_circuits)

{'Circuito da Boavista', 'Hockenheimring', 'Brands Hatch', 'Le Mans', 'Autodromo Enzo e Dino Ferrari', 'Detroit Street Circuit', 'Ain Diab', 'Circuit de Monaco', 'Circuit Paul Ricard', 'Jarama', 'Prince George Circuit', 'Suzuka Circuit', 'Valencia Street Circuit', 'Fair Park', 'Pescara Circuit', 'Circuit Mont-Tremblant', 'Watkins Glen', 'Buddh International Circuit', 'Indianapolis Motor Speedway', 'Circuit of the Americas', 'Bahrain International Circuit', 'Aintree', 'Long Beach', 'AutÃ³dromo Juan y Oscar GÃ¡lvez', 'Rouen-Les-Essarts', 'Circuito de Jerez', 'NÃ¼rburgring', 'Red Bull Ring', 'AutÃ³dromo Hermanos RodrÃ­guez', 'AutÃ³dromo Internacional Nelson Piquet', 'Sepang International Circuit', 'Circuit de Nevers Magny-Cours', 'Istanbul Park', 'Albert Park Grand Prix Circuit', 'AutÃ³dromo do Estoril', 'Zolder', 'MontjuÃ¯c', 'AVUS', 'Riverside International Raceway', 'Circuit de Spa-Francorchamps', 'Silverstone Circuit', 'Circuit Park Zandvoort', 'Okayama International Circuit', 'Kyalami', 'Dijon-Prenois', 'Mosport International Raceway', 'Donington Park', 'Zeltweg', 'Yas Marina Circuit', 'Autodromo Nazionale di Monza', 'Circuit de Pedralbes', 'Fuji Speedway', 'Hungaroring', 'Nivelles-Baulers', 'Circuit de Barcelona-Catalunya', 'Charade Circuit', 'Korean International Circuit', 'Reims-Gueux', 'Marina Bay Street Circuit', 'Shanghai International Circuit', 'Circuit Gilles Villeneuve', 'AutÃ³dromo JosÃ© Carlos Pace', 'Monsanto Park Circuit', 'Sebring International Raceway', 'Adelaide Street Circuit', 'Circuit Bremgarten', 'Scandinavian Raceway', 'Phoenix street circuit'}
{'Caesars Palace'}
{'Las Vegas Strip Street Circuit', 'Baku City Circuit', 'Miami International Autodrome', 'Autodromo Internazionale del Mugello', 'Sochi Autodrom', 'Jeddah Corniche Circuit', 'Las Vegas Street Circuit', 'Losail International Circuit', 'AutÃ³dromo Internacional do Algarve'}

### trying to find the wikipedia page

In [123]:
# Load the data
circuits_df = pd.read_csv('F1Data/circuits.csv')

# Filter for rows where the 'name' column contains 'Vegas'
vegas_rows = circuits_df[circuits_df['name'].str.contains('Vegas', case=False, na=False)]

# Drop the 'country' and 'alt' columns
vegas_rows = vegas_rows.drop(columns=['country', 'alt'])

# Display the filtered DataFrame
vegas_rows

,circuitId,circuitRef,name,location,lat,lng,url
22,80,vegas,Las Vegas Strip Street Circuit,Las Vegas,36.1147,-115.173,https://en.wikipedia.org/wiki/Las_Vegas_Grand_...
43,44,las_vegas,Las Vegas Street Circuit,Nevada,36.1162,-115.174,http://en.wikipedia.org/wiki/Las_Vegas_Street_...

In [125]:
# Print full URLs without truncation
for url in vegas_rows['url']:
    print(url)

https://en.wikipedia.org/wiki/Las_Vegas_Grand_Prix#Circuit
http://en.wikipedia.org/wiki/Las_Vegas_Street_Circuit